blank_lines_upper_bound = 2

condense_wildcard_suffixes = true

imports_indent = "Block"
imports_layout = "HorizontalVertical"

match_block_trailing_comma = true

reorder_imports = true
reorder_imports_in_group = true
reorder_imported_names = true

reorder_modules = true

struct_field_align_threshold = 20

use_try_shorthand = true
