language: rust

rust:
  - stable
  - nightly

cache:
  cargo: true

sudo: required

env:
  global:
  - CARGO_INCREMENTAL=0

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run --example plain
  - cargo run --example term
  - cargo run --example json

jobs:
  allow_failures:
    - rust: nightly-2018-07-07
  include:
    - stage: clippy lints
      rust: nightly-2018-07-07
      env:
        - NIGHTLY=nightly-2018-07-07
        - CLIPPY=0.0.212
      before_install:
        - travis_wait ./.ci/travis-install-clippy.sh
      script:
        - cargo +$NIGHTLY clippy --verbose --all -- -D warnings
    - stage: upload docs
      if: (branch = master) AND (type != pull_request)
      rust: nightly
      script:
        - cargo doc
      deploy:
        provider: pages
        github-token: $GITHUB_TOKEN
        skip-cleanup: true
        local-dir: target/doc

branches:
  only:
    - master
    - develop

notifications:
  email:
    on_success: never
