type = "json"
target = "stdout"
format = "bunyan"
level = "debug"
timestamp = "rfc3339-utc"
newlines = true
pretty = false

# => target
# can be one of
# - "stdout" (default)
# - "stderr"
# - { path = "<file>", mode = "<open-mode>" }

# => target.mode
# can be one of
# - "append" (default, appends-to or creates a file)
# - "truncates" (truncates or creates a file)
# - "new" (requires that a file does not exist previously)

# => format
# can be one of
# - "basic" (default, contains timestamp as ts, level, and message as msg)
# - "tagged" (contains timestamp as ts, level, an optional tag, and the
#   message as msg)
# - "winston" (a winston-style format, contains timestamp, level, an optional
#   tag as label, and the message)
# - "bunyan" (a bunyan-style format, see
#   https://github.com/trentm/node-bunyan#core-fields for details)

# => level
# filter level
# can be one of ["trace", "debug", "info", "warning", "error", "critical"]
# the default is "info"

# => timestamp
# can be one of
# - "rfc3339-utc" (default, UTC time formatted in RFC-3339 style)
# - "rfc3339-local" (local time formatted in RFC-3339 style)

# => newlines
# controls whether each entry should be started on a new line
# defaults to true

# => pretty
# controls whether the JSON should be formatted for readability
# defaults to false
