type = "json"
target = "stdout"
format = "basic"
level = "debug"
timestamp = "rfc3339-utc"
newlines = true
pretty = false

# => target
# can be one of
# - "stdout" (default)
# - "stderr"
# - { path = "<file>", mode = "<open-mode>" }

# => target.mode
# can be one of
# - "append" (default, appends-to or creates a file)
# - "truncates" (truncates or creates a file)
# - "new" (requires that a file does not exist previously)

# => format
# can be one of
# - "basic" (default, repeats every piece of information on each line)

# => level
# filter level
# can be one of ["trace", "debug", "info", "warning", "error", "critical"]
# the default is "info"

# => timestamp
# can be one of
# - "rfc3339-utc" (default, UTC time formatted in RFC-3339 style)
# - "rfc3339-local" (local time formatted in RFC-3339 style)

# => newlines
# controls whether each entry should be started on a new line
# defaults to true

# => pretty
# controls whether the JSON should be formatted for readability
# defaults to false
